### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by kazufukurou** [tyru/skk.vim#28]
Ctrl-Jを押して平仮名で入力できるけど漢字変換が動かない。
```IndexError: string index out of range```
と言うエラーが出ます。SKK-JISYO.Lファイルのパスは正しいと思います。
多分使い方を分かりません。例えば「かんじ」を入力してどうやって「漢字」に変わるんですか。

**Comment by thinca** [comment]
エラーについてはちょっとわかりませんが、「漢字」を入力するには `Kanji<Space>` と入力します。
SKK では、漢字の変換を始めたいところで大文字を入力します。送り仮名がある場合には、そこで更に大文字を入力します。つまり、「感じ」と入力したい場合は「KanJi」と入力します。

**Comment by kazufukurou** [comment]
大文字が必要だと知りませんでした。漢字変換が動いています。エラーの原因はValloric/YouCompleteMeと言うプラグインでした。ありがとうございます。
