### ISSUE TITLE
AZIK 配列を正しい配列に修正

### ISSUE THREAD

**Issue by tyru** [tyru/skk.vim#31]
#30 

> 実は現在 azik ブランチで `let g:skk_keyboard_layout = 'azik'` として使える配列が AZIK ではなく ACT 配列とのこと。
> （http://tyru.hatenablog.com/entry/20101009/skk_vim_azik のコメント欄で教えてもらった情報）

**Comment by mozKomatsu** [comment]
tyru 樣
skk.vim への コメントを書いた moz です。
skk.vim-azik を何とか使えるやうになりました。
私の書き方が悪かつたと思います。azik が act配列なのではなく、私が act しか知らなかつたことが、
そもそも 間違いの原因でした。お作りになられた skk.vim-azic は Dvorak layout で使用する場合には 'jlod' と書いておけば act から改良された jlod を使用できる樣になつてゐます。'azik' と書けば azik を 使用できますので、ここの場の表題は 必要ないものと 思います。
急いで jlod を勉強してゐます。act とかなり 似てゐますが、まだ ピンと来ないので、
CorvusSKK と AquaSKK を jlod 設定にして 慣れるやうにと思つてゐます。

**Comment by tyru** [comment]
なるほど、了解しました。
わざわざありがとうございます。
